"""add tag next_tag_id

Revision ID: 29d169a2d09b
Revises: 9cba7afff76b
Create Date: 2023-05-31 07:43:19.987804

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29d169a2d09b'
down_revision = '9cba7afff76b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tag', sa.Column('next_tag_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_tag_next_tag_id'), 'tag', ['next_tag_id'], unique=False)
    op.create_foreign_key(None, 'tag', 'tag', ['next_tag_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tag', type_='foreignkey')
    op.drop_index(op.f('ix_tag_next_tag_id'), table_name='tag')
    op.drop_column('tag', 'next_tag_id')
    # ### end Alembic commands ###
