"""add_customer_route

Revision ID: 9f4cff797a2b
Revises: 29d169a2d09b
Create Date: 2024-04-19 10:39:52.908098

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9f4cff797a2b'
down_revision = '29d169a2d09b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_user_route',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('user_route', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer_user_route')
    # ### end Alembic commands ###
